version: 2 # use CircleCI 2.0 #
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
            name: Clean Install
            command: ./mvnw clean install

