version: 2.1 # use CircleCI 2.1 #

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.0
    steps:
      - checkout
      - run:
            name: Check Version
            command: java --version
      -run:
            name: Clean Install
            command: ./mvnw clean install
