version: 2.1 # use CircleCI 2.1 #

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.0
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: 1q2w3e
          MYSQL_DATABASE: onlineShopping
          MYSQL_USER: root
          MYSQL_PASSWORD: 1q2w3e
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:


